CREATE DATABASE IF NOT EXISTS Videojuego;
USE Videojuego;

CREATE TABLE IF NOT EXISTS Maestro (
	IDMaestro INT PRIMARY KEY AUTO_INCREMENT,
	Nombre VARCHAR(255) NOT NULL,
	Correo VARCHAR(255) NOT NULL UNIQUE,
	Grupo CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS Alumno (
	Genero CHAR(1) NOT NULL,
	Grupo CHAR(1) NOT NULL,
	NumLista INT NOT NULL,
	IDAlumno INT AUTO_INCREMENT PRIMARY KEY,
	IDMaestro INT NOT NULL,
	FOREIGN KEY (IDMaestro) REFERENCES Maestro(IDMaestro)
);

CREATE TABLE IF NOT EXISTS Nivel (
	NumPreguntas INT NOT NULL,
	NumNivel INT NOT NULL PRIMARY KEY,
	Descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SesionNivel (
	Aciertos INT NOT NULL,
	Errores INT NOT NULL,
	Tiempo TIME NOT NULL,
	NumNivel INT NOT NULL,
	IDAlumno INT NOT NULL,
	Fecha DATE NOT NULL,
	Completado BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (NumNivel) REFERENCES Nivel(NumNivel),
	FOREIGN KEY (IDAlumno) REFERENCES Alumno(IDAlumno)
);

CREATE  TABLE IF NOT EXISTS Pregunta (
	IDPregunta INT PRIMARY KEY AUTO_INCREMENT,
	Texto VARCHAR(255) NOT NULL,
	Respuesta VARCHAR(255) NOT NULL,
	NumNivel INT NOT NULL,
	FOREIGN KEY (NumNivel) REFERENCES Nivel(NumNivel)
)